platform :ios, '12.0'
#source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ZApp' do
	
	pod 'DoraemonKit/Core', :configurations =>['Debug']
	pod 'DoraemonKit/WithGPS', :configurations => ['Debug']
	pod 'DoraemonKit/WithLoad', :configurations => ['Debug']
	pod 'DoraemonKit/WithLogger', :configurations =>['Debug']
	pod 'DoraemonKit/WithDatabase', :configurations => ['Debug']
#	pod 'DoraemonKit/WithMLeaksFinder', :configurations =>['Debug']
	
	pod 'SnapKit'
	pod 'Aspects'
	pod 'YYKit'
	pod 'lottie-ios'
	pod 'FMDB'
	pod 'ZKit'
end
