#!/bin/bash

ENVIRONMENT_VARIABLES_INITIALIZED="1"

# Directory Paths
CONSTRUCTION_HOME=$(cd "$SCRIPT_HOME/../";pwd)
EXPORT_OPTIONS_HOME=$(cd "$CONSTRUCTION_HOME/ExportOptions/";pwd)
PROJECT_HOME=$(cd "$CONSTRUCTION_HOME/../";pwd)
ARCHIVE_HOME="$PROJECT_HOME/archives"
PRODUCT_HOME="$PROJECT_HOME/product"

# Project
PROJECT_NAME="PROJECT_NAME"
PROJECT_TARGET_NAME=$PROJECT_NAME
PROJECT_INFO_PLIST_PATH_DEBUG="$PROJECT_HOME/$PROJECT_NAME/Info.plist"
PROJECT_INFO_PLIST_PATH_RELEASE="$PROJECT_HOME/$PROJECT_NAME/Info.plist"
PROJECT_MARKETING_VERSION_SHOULD_UPDATE="0"
PROJECT_MARKETING_VERSION=""
PROJECT_VERSION_SHOULD_UPDATE="1"
PROJECT_VERSION=`date +"%m.%d.%H.%M"`

# Dependencies
COCOAPODS_REPOSITORIES_SHOULD_UPDATE="0"
COCOAPODS_PODFILE_SHOULD_UPDATE="1"

# Clean
# "Debug": Debug
# "Release": Release
CLEAN_CONFIGURATION_DEBUG="Debug"
CLEAN_CONFIGURATION_RELEASE="Release"

# CONSTRUCTION
# "0": Debug
# "1": App Store Release
CONSTRUCTION_MODE="1"
CONSTRUCTION_CLEAN_DEPENDENCIES_BEFORE_COMPILE="0"
CONSTRUCTION_CLEAN_PRODUCT_BEFORE_COMPILE="1"
CONSTRUCTION_WORKSPACE_PATH="$PROJECT_HOME/$PROJECT_NAME.xcworkspace"

# Export Options plist file
CONSTRUCTION_EXPORT_OPTIONS_PLIST_PATH_DEVELOPMENT="$EXPORT_OPTIONS_HOME/development.plist"
CONSTRUCTION_EXPORT_OPTIONS_PLIST_PATH_DISTRIBUTION="$EXPORT_OPTIONS_HOME/distribution.plist"

# Cooperation
CONSTRUCTION_PROJECT_INFO_PLIST_PATH=$CONSTRUCTION_EXPORT_OPTIONS_PLIST_PATH_DEVELOPMENT
CONSTRUCTION_EXPORT_OPTIONS_PLIST_PATH=$CONSTRUCTION_EXPORT_OPTIONS_PLIST_DEVELOPMENT
CLEAN_CONFIGURATION=$CLEAN_CONFIGURATION_DEBUG
if [ "${CONSTRUCTION_MODE}" = "1" ]; then
    CONSTRUCTION_PROJECT_INFO_PLIST_PATH=$PROJECT_INFO_PLIST_PATH_RELEASE
    CONSTRUCTION_EXPORT_OPTIONS_PLIST_PATH=$CONSTRUCTION_EXPORT_OPTIONS_PLIST_PATH_DISTRIBUTION
    CLEAN_CONFIGURATION=$CLEAN_CONFIGURATION_RELEASE
fi

CONSTRUCTION_ARCHIVE_PATH="$ARCHIVE_HOME/$PROJECT_VERSION.xcarchive"
EXPORT_PRODUCT_PATH="$PRODUCT_HOME/$PROJECT_NAME.ipa"


# upload
UPLOAD_APPLE_API_KEY=
UPLOAD_APPLE_API_ISSUER=

# Check
echo "==== check PROJECT_HOME ===="
if [ ! -d "$PROJECT_HOME" ]; then
    echo "PROJECT_HOME: $PROJECT_HOME Not Found"
    exit 1
fi

echo "==== check PROJECT_NAME ===="
if [ -z "$PROJECT_NAME" ]; then
    echo "PROJECT_NAME: $PROJECT_TARGET_NAME Not Found"
    exit 1
fi

echo "==== check PROJECT_TARGET_NAME ===="
if [ -z "$PROJECT_TARGET_NAME" ]; then
    echo "PROJECT_TARGET_NAME: $PROJECT_TARGET_NAME Not Found"
    exit 1
fi

echo "==== check CONSTRUCTION_PROJECT_INFO_PLIST_PATH ===="
if [ ! -f "$CONSTRUCTION_PROJECT_INFO_PLIST_PATH" ]; then
    echo "CONSTRUCTION_PROJECT_INFO_PLIST_PATH: $CONSTRUCTION_PROJECT_INFO_PLIST_PATH Not Found"
    exit 1
fi

echo "==== check CONSTRUCTION_EXPORT_OPTIONS_PLIST_PATH ===="
if [ ! -f "$CONSTRUCTION_EXPORT_OPTIONS_PLIST_PATH" ]; then
    echo "CONSTRUCTION_EXPORT_OPTIONS_PLIST_PATH: $CONSTRUCTION_EXPORT_OPTIONS_PLIST_PATH Not Found"
    exit 1
fi

echo "==== check ARCHIVE_HOME ===="
if [ ! -d "$ARCHIVE_HOME" ]; then
    echo "make $ARCHIVE_HOME"
    mkdir -p "$ARCHIVE_HOME"
fi

echo "==== check PRODUCT_HOME ===="
if [ ! -d "$PRODUCT_HOME" ]; then
    echo "make $PRODUCT_HOME"
    mkdir -p "$PRODUCT_HOME"
fi
